exports.newsChannels = {
    "newsChannelsContent":[
        {
            "channelName":"Zee News",
            "pageHeaderTopStories":"Top Stories",
            "pageHeaderBusiness":"Business",
            "pageHeaderHealth":"Health",
            "pageHeaderWorld":"World",
            "pageHeaderSports":"Sports",
            "pageHeaderTechnology":"Technology",
            "channelURL":"zeenews",
            "channelTopStories":"topstories",
            "channelBusiness":"business",
            "channelHealth":"health",
            "channelWorld":"world",
            "channelSports":"sports",
            "channelTechnology":"technology"
        },    
        {
            "channelName":"NDTV",
            "pageHeaderTopStories":"Top Stories",
            "pageHeaderBusiness":"Business",
            "pageHeaderHealth":"Health",
            "pageHeaderWorld":"World",
            "pageHeaderSports":"Sports",
            "pageHeaderTechnology":"Technology",
            "channelURL":"ndtv",
            "channelTopStories":"topstories",
            "channelBusiness":"business",
            "channelHealth":"health",
            "channelWorld":"world",
            "channelSports":"sports",
            "channelTechnology":"technology"
        },   
        {
            "channelName":"Times of India",
            "pageHeaderTopStories":"Top Stories",
            "pageHeaderBusiness":"Business",
            "pageHeaderHealth":"Health",
            "pageHeaderWorld":"World",
            "pageHeaderSports":"Sports",
            "pageHeaderTechnology":"Technology",
            "channelURL":"timesofindia",
            "channelTopStories":"topstories",
            "channelBusiness":"business",
            "channelHealth":"health",
            "channelWorld":"world",
            "channelSports":"sports",
            "channelTechnology":"technology"
        },   
        {
            "channelName":"Financial Express",
            "pageHeaderTopStories":"Top Stories",
            "pageHeaderBusiness":"Business",
            "pageHeaderHealth":"Health",
            "pageHeaderWorld":"World",
            "pageHeaderSports":"Sports",
            "pageHeaderTechnology":"Technology",
            "channelURL":"financialexpress",
            "channelTopStories":"topstories",
            "channelBusiness":"business",
            "channelHealth":"health",
            "channelWorld":"world",
            "channelSports":"sports",
            "channelTechnology":"technology"
        },   
        {
            "channelName":"Economic Times",
            "pageHeaderTopStories":"Top Stories",
            "pageHeaderBusiness":"Business",
            "pageHeaderHealth":"Health",
            "pageHeaderWorld":"World",
            "pageHeaderSports":"Sports",
            "pageHeaderTechnology":"Technology",
            "channelURL":"economictimes",
            "channelTopStories":"topstories",
            "channelBusiness":"business",
            "channelHealth":"health",
            "channelWorld":"world",
            "channelSports":"sports",
            "channelTechnology":"technology"
        },   
        {
            "channelName":"India Today",
            "pageHeaderTopStories":"Top Stories",
            "pageHeaderBusiness":"Business",
            "pageHeaderHealth":"Health",
            "pageHeaderWorld":"World",
            "pageHeaderSports":"Sports",
            "pageHeaderTechnology":"Technology",
            "channelURL":"indiatoday",
            "channelTopStories":"topstories",
            "channelBusiness":"business",
            "channelHealth":"health",
            "channelWorld":"world",
            "channelSports":"sports",
            "channelTechnology":"technology"
        },   
        {
            "channelName":"Business Standard",
            "pageHeaderTopStories":"Top Stories",
            "pageHeaderBusiness":"Business",
            "pageHeaderHealth":"Health",
            "pageHeaderWorld":"World",
            "pageHeaderSports":"Sports",
            "pageHeaderTechnology":"Technology",
            "channelURL":"businessstandard",
            "channelTopStories":"topstories",
            "channelBusiness":"business",
            "channelHealth":"health",
            "channelWorld":"world",
            "channelSports":"sports",
            "channelTechnology":"technology"
        },   
        {
            "channelName":"News18",
            "pageHeaderTopStories":"Top Stories",
            "pageHeaderBusiness":"Business",
            "pageHeaderHealth":"Health",
            "pageHeaderWorld":"World",
            "pageHeaderSports":"Sports",
            "pageHeaderTechnology":"Technology",
            "channelURL":"news18",
            "channelTopStories":"topstories",
            "channelBusiness":"business",
            "channelHealth":"health",
            "channelWorld":"world",
            "channelSports":"sports",
            "channelTechnology":"technology"
        },   
        {
            "channelName":"Hindustan Times",
            "pageHeaderTopStories":"Top Stories",
            "pageHeaderBusiness":"Business",
            "pageHeaderHealth":"Health",
            "pageHeaderWorld":"World",
            "pageHeaderSports":"Sports",
            "pageHeaderTechnology":"Technology",
            "channelURL":"hindustantimes",
            "channelTopStories":"topstories",
            "channelBusiness":"business",
            "channelHealth":"health",
            "channelWorld":"world",
            "channelSports":"sports",
            "channelTechnology":"technology"
        },   
    ]
}